import "./globals.css";
import type { Metadata } from "next";
import { Inter } from "next/font/google";
import Link from "next/link";

const inter = Inter({ subsets: ["latin"] });

export const metadata: Metadata = {
  title: "Create Next App",
  description: "Generated by create next app",
};

export default function RootLayout({
  children,
}: {
  children: React.ReactNode;
}) {
  return (
    <html lang="en">
      <body className={inter.className}>
        <nav>
          <ul
            style={{
              listStyle: "none",
              display: "flex",
              justifyContent: "space-between",
            }}
          >
            <li>
              <Link href="/">Home Route</Link>
            </li>
            <li>
              <Link href="/test">Test Route</Link>
            </li>
          </ul>
        </nav>
        {children}
      </body>
    </html>
  );
}
